### ISSUE TITLE
"Unable to load" Message

### ISSUE THREAD

**Issue by PeterHurt** [SamGarlick/VelvetDawn#5]
Server Environment: Ubuntu 22.10, fresh repository pull, requirements met
Web clients: Edge 108.0.1462.76, Chrome 108.0.5359.125

A couple of seconds after loading the webpage and interface, a browser message box is shown, with the text:
```
127.0.0.1:666 says:
Unable to load
```
This is being shown from Line 2885 in 'src/frontend/dist/app.js'

VS Code has also flagged an issue with 'src/frontend/tsconfig.json', although it's probably unrelated:
```
Cannot find type definition file for 'jest'.
  The file is in the program because:
    Entry point of type library 'jest' specified in compilerOptions
```

**Comment by SamGarlick** [comment]
Spoken offline, resolving.
